services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend:8000/api # 👈 Passed to Vite at build time
    container_name: vite-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
